name: Update inputs
on:
  schedule:
    - cron: "0 12 * * *" # UTC
  workflow_dispatch:
jobs:
  update-inputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
    - uses: actions/checkout@v4
      with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false
    - uses: cachix/install-nix-action@v25
    - uses: DeterminateSystems/update-flake-lock@v21
      with:
        token: ${{ steps.app-token.outputs.token }}
        inputs: "neovim-nightly-overlay nixpkgs"
    - name: Setup merge
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr merge --auto --delete-branch --squash "update_flake_lock_action"
